[package]
name = "abc-uiautomation"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3"
chrono = "0.4"
uiautomation = "0.7"
